### ISSUE TITLE
Compile on Mac

### ISSUE THREAD

**Issue by eliabieri** [beckdac/ESP8266-transparent-bridge#11]
how can i compile this on a mac?

**Comment by dvv** [comment]
I can't build it on linux:
```
make: Nothing to be done for 'FORCE'.
```

**Comment by eliabieri** [comment]
I get the exact same error on mac!

-- 

Elia Bieri
whateveryouwant@eliabieri.com

**Comment by sticilface** [comment]
Get the same error on my ubuntu installation

**Comment by beckdac** [comment]
I build this on a Mac and a Linux box.  Make sure you have properly installed the SDK.
