### ISSUE TITLE
Can't change the WiFi channel.

### ISSUE THREAD

**Issue by firew4lker** [beckdac/ESP8266-transparent-bridge#12]
I am not able to change the WiFi channel. I is always 6. The command I am using is

+++AT AP myssid 12345678 3 10

The software will respond OK, but the channel will not change. 

Can someone verify?

**Comment by beckdac** [comment]
Did you reset the unit after the change?

--- Original Message ---

**Comment by firew4lker** [comment]
Yes. Reset, and power cycle.

**Comment by firew4lker** [comment]
I will try a re-flash tomorow.

**Comment by openSoftMan** [comment]
I have the same issue; channel doesn't change.  The command is accepted, but always stays at 6.

**Comment by firew4lker** [comment]
Can the channel be changed while in mode 3 (AP and STA)? Maybe if it have to connect to an AP, it must transmit to the same channel?

**Comment by firew4lker** [comment]
Disregard the above. I thought my home AP was at channel 6 also. But no (it actually 11).

**Comment by firew4lker** [comment]
It seems the when in MODE 3 the AP channel is always the channel the STA is connected to.

**Comment by beckdac** [comment]
@firew4lker yes, this is the SDK behavior.  Thanks for the notifications.
