### ISSUE TITLE
AT GPIO2 command does not work

### ISSUE THREAD

**Issue by fvpalha** [beckdac/ESP8266-transparent-bridge#16]
Hi.

The command:
++AT GPIO2 (0/1/2) - does not work.

How I can fix this error?

**Comment by ArnieO** [comment]
What you are looking for is the extension made by  Joost van den Broek (jvandenbroek). You find the version with the +++AT GPIO2 command here: 
https://github.com/jvandenbroek/ESP8266-transparent-bridge
And it works! :-)

**Comment by fvpalha** [comment]
Thank you Arnie.

**Comment by beckdac** [comment]
I have merged his (fantastic) changes back into this repo.

**Comment by fvpalha** [comment]
Thank you, bechdac.
