### ISSUE TITLE
How to change soft ap ipaddress

### ISSUE THREAD

**Issue by dogrocker** [beckdac/ESP8266-transparent-bridge#17]
I want to change default IP address of soft AP
now it 192.168.4.1

How can I change it to 192.168.5.1 or something I want?

Thanks.

**Comment by fvpalha** [comment]
Hi.

I think that is defined on external library "esp-lwip" (https://github.com/kadamski/esp-lwip).
The SDK have the file "C:\Espressif\ESP8266_SDK\lib\liblwip.a"

**Comment by beckdac** [comment]
I have not been able to find a solution to this.  As @fvpalha mentioned, this is API dependent.
