### ISSUE TITLE
No new Wifi after flashing

### ISSUE THREAD

**Issue by sigrokBlack** [beckdac/ESP8266-transparent-bridge#24]
Hi,
after successfully flashing your firmware and power cycling, no wifi networks appears on my Pc/Android.

What can I do?

Greetings Joshua

**Comment by sigrokBlack** [comment]
Sloved It! When you used NODEMCU before on the module do this :+1: http://www.rei-labs.net/esp8266-update-firmware-to-change-the-baudrate/1/

**Comment by MustafaFayez** [comment]
@sigrokBlack  I have the same problem: after flashing transparent-bridge my pc/tablet can't see the module's AP!! I tried to flash the basic AT firmware first and config wifi AP and then flash the transparent-bridge firmware again, it didn't work. How you solved it?

**Comment by sigrokBlack** [comment]
Hi, in my last post, there is a link with detailed instructions. The main problem is that firmwares like nodemcu are saving their files all over the flash, so you have to earse the flash chip completly.
Regards Joshua

**Comment by beckdac** [comment]
Yes. I can confirm this.
