### ISSUE TITLE
Garbage in UART0 on start ESP8266

### ISSUE THREAD

**Issue by fvpalha** [beckdac/ESP8266-transparent-bridge#27]
Hi @beckdac .

I would like to clean the TX FIFO before initialize the UART0.

The GPIO15 signal the UART0 config.
The GPIO4 signal the uart_tx_char() working.

How I can avoid this?
![2015-06-02 10 20 32](https://cloud.githubusercontent.com/assets/2786212/7938072/12a9b9c6-091a-11e5-9294-821e455d1ffc.jpg)

**Comment by beckdac** [comment]
Sorry for the long delay, but I'll assume you figured it out.  I suspect that is I/O from the chip bootloader and short of using a custom baud rate.  If you find the baud rate for the esp8266 boot loader and can use that value for your application it might be possible to screen out those booting offending commands.

Or just make your client side app more robust in the face of gibberish.
