### ISSUE TITLE
ap ssid issue

### ISSUE THREAD

**Issue by alonewolfx2** [beckdac/ESP8266-transparent-bridge#3]
i can compile source and i tried something. its working fine but ap changing over tcp telnet not working correctly. it catch first 4 char ssid from tcp command. its giving right ssid with +++at ap command but i am looking wireless network names and always just 4 char. ex i am sending +++AT AP newSSID and its saying SSID=newSSID but i saw just newS in wireless network

**Comment by petgit** [comment]
in config_cmd_ap I set ap_conf.ssid_len for the ssid string in my pull request. It worked for me.

**Comment by beckdac** [comment]
This pull request has been merged.
