### ISSUE TITLE
question: Static settings

### ISSUE THREAD

**Issue by M3gaFr3ak** [beckdac/ESP8266-transparent-bridge#30]
First: How do i set the baudrate for static settings?
Second: Do static settings completely deactivate the parsing of +++AT commands?

**Comment by Cougar** [comment]
1. Defaults are in https://github.com/beckdac/ESP8266-transparent-bridge/blob/master/user/flash_param.c#L48

2. Yes. Look at https://github.com/beckdac/ESP8266-transparent-bridge/blob/master/user/server.c#L102-L106

**Comment by M3gaFr3ak** [comment]
thanks!

another little question:
Currently i am using that as a bridge for controlling an led cube over wifi. but it has a delay of ~half a second. is that some sort of computation delay inside the esp?

**Comment by beckdac** [comment]
Nope.  That is particularly long.  When you ping the device what is your roundtrip time?  I rarely see more than 10s of milliseconds.
