### ISSUE TITLE
Doesn't compile with esp-open-sdk

### ISSUE THREAD

**Issue by pholat** [beckdac/ESP8266-transparent-bridge#43]
gcc version 4.8.2 (crosstool-NG 1.20.0)
Fail on:

> $ make
CC user/config.c
user/config.c: In function 'my_strdup':
user/config.c:153:2: error: too many arguments to function 'pvPortMalloc'
  if (!(copy = os_malloc((u_int)len)))
  ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:33:7: note: declared here
 void *pvPortMalloc(size_t xWantedSize);
       ^
user/config.c: In function 'config_parse_args':
user/config.c:162:2: error: too many arguments to function 'pvPortMalloc'
  char **argv = (char **)os_malloc(sizeof(char *) * MAX_ARGS); // note fixed length
  ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:33:7: note: declared here
 void *pvPortMalloc(size_t xWantedSize);
       ^
user/config.c: In function 'config_parse_args_free':
user/config.c:181:4: error: too many arguments to function 'vPortFree'
    os_free(argv[i]);
    ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:36:6: note: declared here
 void vPortFree(void *ptr);
      ^
user/config.c:183:2: error: too many arguments to function 'vPortFree'
  os_free(argv);
  ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:36:6: note: declared here
 void vPortFree(void *ptr);
      ^
user/config.c: In function 'config_parse':
user/config.c:461:2: error: too many arguments to function 'pvPortMalloc'
  char *lbuf = (char *)os_malloc(len + 1), **argv;
  ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:33:7: note: declared here
 void *pvPortMalloc(size_t xWantedSize);
       ^
user/config.c:505:2: error: too many arguments to function 'vPortFree'
  os_free(lbuf);
  ^
In file included from user/config.c:4:0:
include/espmissingincludes.h:36:6: note: declared here
 void vPortFree(void *ptr);
      ^
make: *** [build/user/config.o] Error 1

might be connected to:
http://www.esp8266.com/viewtopic.php?f=34&t=5748

**Comment by pholat** [comment]
Update:
-> removing espmissingincludes.h solves compilation errors.

**Comment by beckdac** [comment]
Thank you.
